/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/test": {
    get: operations["test"];
  };
  "/room-configuration": {
    post: operations["generateRoomConfiguration"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    IRoomCreationParams: {
      roomDescription: {
        widthInMeters: number;
        depthInMeters: number;
        heightInMeters: number;
        /** @enum {string} */
        roomCategory: "living room" | "dining room" | "family room" | "office" | "bedroom" | "kitchen" | "conference room" | "generic";
      };
      fillTarget: number;
      /** @enum {string} */
      furniturePlacementType: "llm" | "random" | "autointeriorblog";
      /** @enum {string} */
      furnitureSelectionType: "random" | "matching search";
      furnitureSearchSelectionKeywords?: string[];
    };
    IRoomConfiguration: {
      id: string;
      imported_room_configuration?: string;
      prompt?: string;
      name?: string;
      area_size_x: number;
      area_size_z: number;
      objects: {
          id?: string;
          model_id?: string;
          model_location?: string;
          name?: string;
          category?: string;
          color?: string;
          x?: number;
          y?: number;
          z?: number;
          orientation?: number;
        }[];
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  test: {
    responses: {
      /** @description OK */
      200: {
        content: {
          "application/json": {
            status: string;
            message: string;
            data?: Record<string, never>;
          };
        };
      };
    };
  };
  generateRoomConfiguration: {
    requestBody: {
      content: {
        "application/json": {
          roomDescription: {
            widthInMeters: number;
            depthInMeters: number;
            heightInMeters: number;
            /** @enum {string} */
            roomCategory: "living room" | "dining room" | "family room" | "office" | "bedroom" | "kitchen" | "conference room" | "generic";
          };
          fillTarget: number;
          /** @enum {string} */
          furniturePlacementType: "llm" | "random" | "autointeriorblog";
          /** @enum {string} */
          furnitureSelectionType: "random" | "matching search";
          furnitureSearchSelectionKeywords?: string[];
        };
      };
    };
    responses: {
      /** @description OK */
      201: {
        content: {
          "application/json": {
            status: string;
            message: string;
            data?: Record<string, never>;
          };
        };
      };
    };
  };
}
