/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/test": {
    get: operations["test"];
  };
  "/room-configuration": {
    post: operations["generateRoomConfiguration"];
  };
}

export interface components {
  schemas: {
    IRoomCreationParams: {
      roomDescription: {
        widthInMeters: number;
        depthInMeters: number;
        heightInMeters: number;
        roomCategory:
          | "living room"
          | "dining room"
          | "family room"
          | "office"
          | "bedroom"
          | "kitchen"
          | "conference room"
          | "generic";
      };
      fillTarget: number;
      furniturePlacementType: "llm" | "random" | "autointeriorblog";
      furnitureSelectionType: "random" | "matching search";
      furnitureSearchSelectionKeywords?: string[];
    };
    IRoomConfiguration: {
      id: string;
      imported_room_configuration?: string;
      prompt?: string;
      name?: string;
      area_size_x: number;
      area_size_z: number;
      objects: {
        id?: string;
        model_id?: string;
        model_location?: string;
        name?: string;
        category?: string;
        color?: string;
        x?: number;
        y?: number;
        z?: number;
        orientation?: number;
      }[];
    };
  };
}

export interface operations {
  test: {
    responses: {
      /** OK */
      200: {
        content: {
          "application/json": {
            status: string;
            message: string;
            data?: { [key: string]: any };
          };
        };
      };
    };
  };
  generateRoomConfiguration: {
    responses: {
      /** OK */
      201: {
        content: {
          "application/json": {
            status: string;
            message: string;
            data?: { [key: string]: any };
          };
        };
      };
    };
    requestBody: {
      content: {
        "application/json": {
          roomDescription: {
            widthInMeters: number;
            depthInMeters: number;
            heightInMeters: number;
            roomCategory:
              | "living room"
              | "dining room"
              | "family room"
              | "office"
              | "bedroom"
              | "kitchen"
              | "conference room"
              | "generic";
          };
          fillTarget: number;
          furniturePlacementType: "llm" | "random" | "autointeriorblog";
          furnitureSelectionType: "random" | "matching search";
          furnitureSearchSelectionKeywords?: string[];
        };
      };
    };
  };
}
